/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  TaskManagerPlugin: () => TaskManagerPlugin,
  default: () => TaskManagerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/tasks/RRuleParser.ts
var RFC_DAY_TO_INDEX = {
  SU: 0,
  MO: 1,
  TU: 2,
  WE: 3,
  TH: 4,
  FR: 5,
  SA: 6
};
var INDEX_TO_RFC_DAY = ["SU", "MO", "TU", "WE", "TH", "FR", "SA"];
var RRuleParser = class {
  /**
   * Parse an RRULE string into a RepeatConfig. Returns null on failure.
   */
  static fromRRule(rrule) {
    var _a;
    const raw = rrule.replace(/^RRULE:/i, "").trim();
    const parts = {};
    for (const segment of raw.split(";")) {
      const eq = segment.indexOf("=");
      if (eq === -1) continue;
      parts[segment.slice(0, eq).toUpperCase()] = segment.slice(eq + 1);
    }
    const freqRaw = (_a = parts["FREQ"]) == null ? void 0 : _a.toUpperCase();
    if (!freqRaw || !["DAILY", "WEEKLY", "MONTHLY", "YEARLY"].includes(freqRaw)) {
      return null;
    }
    const freq = freqRaw;
    const config = {
      freq,
      interval: parts["INTERVAL"] ? parseInt(parts["INTERVAL"], 10) : 1
    };
    if (parts["BYDAY"]) {
      config.byday = parts["BYDAY"].split(",").map((d) => d.trim().toUpperCase());
    }
    if (parts["BYMONTHDAY"]) {
      config.bymonthday = parts["BYMONTHDAY"].split(",").map(Number);
    }
    if (parts["BYSETPOS"]) {
      config.bysetpos = parts["BYSETPOS"].split(",").map(Number);
    }
    if (parts["COUNT"]) {
      config.count = parseInt(parts["COUNT"], 10);
    }
    if (parts["UNTIL"]) {
      const u = parts["UNTIL"].replace(/T.*$/, "");
      if (u.length === 8) {
        config.until = `${u.slice(0, 4)}-${u.slice(4, 6)}-${u.slice(6, 8)}`;
      } else {
        config.until = u;
      }
    }
    return config;
  }
  /**
   * Serialize a RepeatConfig to an RRULE string.
   */
  static toRRule(config) {
    const parts = [`FREQ=${config.freq}`];
    if (config.interval && config.interval > 1) {
      parts.push(`INTERVAL=${config.interval}`);
    }
    if (config.byday && config.byday.length > 0) {
      parts.push(`BYDAY=${config.byday.join(",")}`);
    }
    if (config.bymonthday && config.bymonthday.length > 0) {
      parts.push(`BYMONTHDAY=${config.bymonthday.join(",")}`);
    }
    if (config.bysetpos && config.bysetpos.length > 0) {
      parts.push(`BYSETPOS=${config.bysetpos.join(",")}`);
    }
    if (config.count != null) {
      parts.push(`COUNT=${config.count}`);
    }
    if (config.until) {
      parts.push(`UNTIL=${config.until.replace(/-/g, "")}`);
    }
    return parts.join(";");
  }
  /**
   * Calculate the next due date after `currentDue`.
   * Returns null if the series has ended.
   */
  static calculateNextDate(currentDue, config) {
    const base = /* @__PURE__ */ new Date(currentDue + "T12:00:00Z");
    let next;
    switch (config.freq) {
      case "DAILY":
        next = this.addDays(base, config.interval);
        break;
      case "WEEKLY":
        next = this.nextWeeklyDate(base, config);
        break;
      case "MONTHLY":
        next = this.nextMonthlyDate(base, config);
        break;
      case "YEARLY":
        next = new Date(base);
        next.setUTCFullYear(next.getUTCFullYear() + config.interval);
        break;
    }
    const nextStr = this.toDateStr(next);
    if (this.isSeriesEnded(config, nextStr)) return null;
    return nextStr;
  }
  /**
   * Returns true when the series should end at or before `candidateDue`.
   */
  static isSeriesEnded(config, candidateDue) {
    if (config.count != null && config.count <= 1) return true;
    if (config.until && candidateDue > config.until) return true;
    return false;
  }
  /**
   * Returns a new RepeatConfig with count decremented by 1.
   * Returns undefined if the series would end (count hits 0).
   */
  static decrementCount(config) {
    if (config.count == null) return config;
    const next = config.count - 1;
    if (next <= 0) return void 0;
    return { ...config, count: next };
  }
  /**
   * Generate read-only ghost occurrences for a recurring task within [rangeStart, rangeEnd].
   */
  static generateOccurrences(task, rangeStart, rangeEnd, maxOccurrences = 200) {
    var _a, _b, _c;
    if (!task.repeat || task.repeatParentId || task.status >= 2 || !task.dueDate) {
      return [];
    }
    const ghosts = [];
    let config = { ...task.repeat };
    const baseDue = task.dueDate.split(" ")[0];
    const dueTimePart = task.dueDate.includes(" ") ? task.dueDate.split(" ")[1] : null;
    const baseStart = (_b = (_a = task.startDate) == null ? void 0 : _a.split(" ")[0]) != null ? _b : null;
    const startTimePart = ((_c = task.startDate) == null ? void 0 : _c.includes(" ")) ? task.startDate.split(" ")[1] : null;
    let nextDue = this.calculateNextDate(baseDue, config);
    let iterations = 0;
    while (nextDue && nextDue <= rangeEnd && iterations < maxOccurrences) {
      iterations++;
      if (nextDue >= rangeStart) {
        let ghostStartDate;
        if (baseStart && startTimePart) {
          ghostStartDate = `${nextDue} ${startTimePart}`;
        } else if (baseStart) {
          ghostStartDate = nextDue;
        }
        ghosts.push({
          id: `ghost-${task.id}-${nextDue}`,
          filePath: task.filePath,
          title: task.title,
          dueDate: dueTimePart ? `${nextDue} ${dueTimePart}` : nextDue,
          startDate: ghostStartDate,
          duration: task.duration,
          priority: task.priority,
          status: 0,
          isAllDay: task.isAllDay,
          tags: task.tags,
          group: task.group,
          isGhost: true
        });
      }
      if (config.count != null) {
        if (config.count <= 1) break;
        config = { ...config, count: config.count - 1 };
      }
      nextDue = this.calculateNextDate(nextDue, config);
    }
    return ghosts;
  }
  // ── Private helpers ──────────────────────────────────────────────────────
  static addDays(date, days) {
    const d = new Date(date);
    d.setUTCDate(d.getUTCDate() + days);
    return d;
  }
  static nextWeeklyDate(base, config) {
    if (!config.byday || config.byday.length === 0) {
      return this.addDays(base, 7 * config.interval);
    }
    const targetDays = new Set(
      config.byday.map((d) => RFC_DAY_TO_INDEX[d]).filter((n) => n !== void 0)
    );
    const windowEnd = this.addDays(base, 7 * config.interval);
    let cursor = this.addDays(base, 1);
    while (cursor <= windowEnd) {
      if (targetDays.has(cursor.getUTCDay())) return cursor;
      cursor = this.addDays(cursor, 1);
    }
    return windowEnd;
  }
  static nextMonthlyDate(base, config) {
    const target = new Date(base);
    target.setUTCMonth(target.getUTCMonth() + config.interval);
    if (config.bysetpos && config.bysetpos.length > 0 && config.byday && config.byday.length > 0) {
      return this.nthWeekdayOfMonth(
        target.getUTCFullYear(),
        target.getUTCMonth(),
        config.byday[0],
        config.bysetpos[0]
      );
    }
    if (config.bymonthday && config.bymonthday.length > 0) {
      const day = config.bymonthday[0];
      const result = new Date(target);
      if (day < 0) {
        result.setUTCMonth(result.getUTCMonth() + 1, 0);
        result.setUTCDate(result.getUTCDate() + day + 1);
      } else {
        result.setUTCDate(day);
      }
      return result;
    }
    return target;
  }
  /**
   * Returns the date of the Nth occurrence of a weekday in a given month.
   */
  static nthWeekdayOfMonth(year, month, byDay, bySetPos) {
    const m = byDay.match(/^(-?\d+)?([A-Z]{2})$/);
    const dayCode = m ? m[2] : byDay;
    const embeddedPos = m && m[1] ? parseInt(m[1], 10) : null;
    const pos = embeddedPos != null ? embeddedPos : bySetPos;
    const targetWeekday = RFC_DAY_TO_INDEX[dayCode];
    if (targetWeekday === void 0) {
      return new Date(Date.UTC(year, month, 1, 12, 0, 0));
    }
    if (pos > 0) {
      const firstOfMonth = new Date(Date.UTC(year, month, 1, 12, 0, 0));
      let offset = (targetWeekday - firstOfMonth.getUTCDay() + 7) % 7;
      const firstOccurrence = new Date(firstOfMonth);
      firstOccurrence.setUTCDate(1 + offset);
      firstOccurrence.setUTCDate(firstOccurrence.getUTCDate() + (pos - 1) * 7);
      return firstOccurrence;
    } else {
      const lastOfMonth = new Date(Date.UTC(year, month + 1, 0, 12, 0, 0));
      let offset = (lastOfMonth.getUTCDay() - targetWeekday + 7) % 7;
      const lastOccurrence = new Date(lastOfMonth);
      lastOccurrence.setUTCDate(lastOfMonth.getUTCDate() - offset);
      lastOccurrence.setUTCDate(lastOccurrence.getUTCDate() + (pos + 1) * 7);
      return lastOccurrence;
    }
  }
  static toDateStr(date) {
    const y = date.getUTCFullYear();
    const m = (date.getUTCMonth() + 1).toString().padStart(2, "0");
    const d = date.getUTCDate().toString().padStart(2, "0");
    return `${y}-${m}-${d}`;
  }
  /** Convert JS weekday index (0=Sun) to RFC day code */
  static indexToRfcDay(index) {
    var _a;
    return (_a = INDEX_TO_RFC_DAY[index]) != null ? _a : "SU";
  }
  /** Convert RFC day code to JS weekday index */
  static rfcDayToIndex(code) {
    var _a;
    return (_a = RFC_DAY_TO_INDEX[code.toUpperCase()]) != null ? _a : 0;
  }
};

// src/tasks/TaskManager.ts
var TaskManager = class {
  constructor() {
    this.tasks = /* @__PURE__ */ new Map();
  }
  /**
   * Parse a markdown line into a task object.
   * Expected format: - [ ] Task title 📅2024-01-15 ⏳2024-01-10 🔼 🏷️work,urgent 🔁FREQ=WEEKLY;BYDAY=MO
   */
  static parseTaskLine(line, filePath, lineNum) {
    var _a, _b, _c;
    const checkboxMatch = line.match(/^(\s*)[-*]\s+\[([ xX>\/-])\]\s+(.*)$/);
    if (!checkboxMatch) return null;
    const [, indent, checkbox, content] = checkboxMatch;
    const status = this.parseCheckboxStatus(checkbox);
    const { title, metadata } = this.parseTaskContent(content);
    const id = `${filePath}:${lineNum}`;
    return {
      id,
      filePath,
      line: lineNum,
      title,
      status,
      priority: (_a = metadata.priority) != null ? _a : 0 /* None */,
      tags: (_b = metadata.tags) != null ? _b : [],
      dueDate: metadata.dueDate,
      startDate: metadata.startDate,
      completedDate: metadata.completedDate,
      duration: metadata.duration,
      isAllDay: (_c = metadata.isAllDay) != null ? _c : true,
      repeat: metadata.repeat,
      group: metadata.group,
      content: line
    };
  }
  /**
   * Parse checkbox character to TaskStatus
   */
  static parseCheckboxStatus(checkbox) {
    switch (checkbox.toLowerCase()) {
      case "x":
        return 2 /* Completed */;
      case ">":
        return 1 /* InProgress */;
      case "-":
        return 3 /* Cancelled */;
      case "/":
        return 1 /* InProgress */;
      default:
        return 0 /* Pending */;
    }
  }
  /**
   * Parse task content and extract metadata
   */
  static parseTaskContent(content) {
    const metadata = {
      tags: []
    };
    let title = content;
    const dueDateMatch = title.match(/📅\s*(\d{4}-\d{2}-\d{2}(?:\s+\d{2}:\d{2})?)/);
    if (dueDateMatch) {
      metadata.dueDate = dueDateMatch[1];
      title = title.replace(dueDateMatch[0], "").trim();
    }
    const startDateMatch = title.match(/⏳\s*(\d{4}-\d{2}-\d{2}(?:\s+\d{2}:\d{2})?)/);
    if (startDateMatch) {
      metadata.startDate = startDateMatch[1];
      title = title.replace(startDateMatch[0], "").trim();
    }
    const completedDateMatch = title.match(/✅\s*(\d{4}-\d{2}-\d{2})/);
    if (completedDateMatch) {
      metadata.completedDate = completedDateMatch[1];
      title = title.replace(completedDateMatch[0], "").trim();
    }
    const priorityMatch = title.match(/(⏫|🔼|🔽)/);
    if (priorityMatch) {
      switch (priorityMatch[1]) {
        case "\u23EB":
          metadata.priority = 3 /* Urgent */;
          break;
        case "\u{1F53C}":
          metadata.priority = 2 /* High */;
          break;
        case "\u{1F53D}":
          metadata.priority = -1 /* Low */;
          break;
      }
      title = title.replace(priorityMatch[0], "").trim();
    }
    const tagEmojiMatch = title.match(/🏷️\s*([^\s]+)/);
    if (tagEmojiMatch) {
      metadata.tags = tagEmojiMatch[1].split(",").map((t) => t.trim());
      title = title.replace(tagEmojiMatch[0], "").trim();
    }
    const hashtagMatches = title.match(/#(\S+)/g);
    if (hashtagMatches) {
      const tags = hashtagMatches.map((m) => m.slice(1));
      metadata.tags.push(...tags);
      title = title.replace(/#\S+/g, "").trim();
    }
    const repeatMatch = title.match(/🔁\s*(RRULE:)?(.+?)(?=\s*📅|🏷️|⏳|✅|⏫|🔼|🔽|$)/);
    if (repeatMatch) {
      const rruleStr = repeatMatch[2].trim();
      const repeat = RRuleParser.fromRRule(rruleStr.startsWith("RRULE:") ? rruleStr : `RRULE:${rruleStr}`);
      if (repeat) {
        metadata.repeat = repeat;
      }
      title = title.replace(repeatMatch[0], "").trim();
    }
    const groupMatch = title.match(/📁\s*(\S+)/);
    if (groupMatch) {
      metadata.group = groupMatch[1];
      title = title.replace(groupMatch[0], "").trim();
    }
    const durationMatch = title.match(/⏱️\s*(\d+)/);
    if (durationMatch) {
      metadata.duration = parseInt(durationMatch[1], 10);
      title = title.replace(durationMatch[0], "").trim();
    }
    title = title.replace(/\s+/g, " ").trim();
    return { title, metadata };
  }
  /**
   * Serialize a task back to markdown format
   */
  static serializeTask(task) {
    let line = "- [";
    switch (task.status) {
      case 2 /* Completed */:
        line += "x";
        break;
      case 1 /* InProgress */:
        line += ">";
        break;
      case 3 /* Cancelled */:
        line += "-";
        break;
      default:
        line += " ";
        break;
    }
    line += `] ${task.title}`;
    if (task.startDate) {
      line += ` \u23F3${task.startDate}`;
    }
    if (task.dueDate) {
      line += ` \u{1F4C5}${task.dueDate}`;
    }
    if (task.completedDate) {
      line += ` \u2705${task.completedDate}`;
    }
    switch (task.priority) {
      case 3 /* Urgent */:
        line += " \u23EB";
        break;
      case 2 /* High */:
        line += " \u{1F53C}";
        break;
      case -1 /* Low */:
        line += " \u{1F53D}";
        break;
    }
    if (task.tags && task.tags.length > 0) {
      line += ` \u{1F3F7}\uFE0F${task.tags.join(",")}`;
    }
    if (task.group) {
      line += ` \u{1F4C1}${task.group}`;
    }
    if (task.duration) {
      line += ` \u23F1\uFE0F${task.duration}`;
    }
    if (task.repeat) {
      line += ` \u{1F501}${RRuleParser.toRRule(task.repeat)}`;
    }
    return line;
  }
  /**
   * Filter tasks based on code block parameters
   */
  static filterTasks(tasks, params) {
    let filtered = [...tasks];
    if (!params.showCompleted) {
      filtered = filtered.filter((t) => t.status !== 2 /* Completed */);
    }
    if (!params.showCancelled) {
      filtered = filtered.filter((t) => t.status !== 3 /* Cancelled */);
    }
    if (params.groups && params.groups.length > 0) {
      filtered = filtered.filter((t) => t.group && params.groups.includes(t.group));
    }
    if (params.tags && params.tags.length > 0) {
      filtered = filtered.filter(
        (t) => t.tags.some((tag) => params.tags.includes(tag))
      );
    }
    if (params.dateRange) {
      const { start, end } = this.parseDateRange(params.dateRange);
      if (start && end) {
        filtered = filtered.filter((t) => {
          if (!t.dueDate) return false;
          const dueDate = t.dueDate.split(" ")[0];
          return dueDate >= start && dueDate <= end;
        });
      }
    }
    if (params.filter) {
      const filterLower = params.filter.toLowerCase();
      filtered = filtered.filter((t) => {
        return t.title.toLowerCase().includes(filterLower) || t.tags.some((tag) => tag.toLowerCase().includes(filterLower)) || t.group && t.group.toLowerCase().includes(filterLower);
      });
    }
    if (params.limit && params.limit > 0) {
      filtered = filtered.slice(0, params.limit);
    }
    return filtered;
  }
  /**
   * Sort tasks based on parameters
   */
  static sortTasks(tasks, sortBy, sortOrder = "asc") {
    const sorted = [...tasks];
    if (!sortBy) {
      return sorted.sort((a, b) => {
        const dateCompare = this.compareDates(a.dueDate, b.dueDate);
        if (dateCompare !== 0) return dateCompare;
        return b.priority - a.priority;
      });
    }
    sorted.sort((a, b) => {
      var _a, _b;
      let result = 0;
      switch (sortBy) {
        case "dueDate":
          result = this.compareDates(a.dueDate, b.dueDate);
          break;
        case "startDate":
          result = this.compareDates(a.startDate, b.startDate);
          break;
        case "priority":
          result = b.priority - a.priority;
          break;
        case "title":
          result = a.title.localeCompare(b.title);
          break;
        case "group":
          result = ((_a = a.group) != null ? _a : "").localeCompare((_b = b.group) != null ? _b : "");
          break;
        case "status":
          result = a.status - b.status;
          break;
        default:
          result = 0;
      }
      return sortOrder === "desc" ? -result : result;
    });
    return sorted;
  }
  /**
   * Group tasks by a field
   */
  static groupTasksBy(tasks, groupBy) {
    var _a;
    const groups = /* @__PURE__ */ new Map();
    for (const task of tasks) {
      let key;
      switch (groupBy) {
        case "status":
          key = this.getStatusLabel(task.status);
          break;
        case "priority":
          key = this.getPriorityLabel(task.priority);
          break;
        case "group":
          key = (_a = task.group) != null ? _a : "No Group";
          break;
        case "tags":
          key = task.tags.length > 0 ? task.tags.join(", ") : "No Tags";
          break;
        default:
          key = "All";
      }
      if (!groups.has(key)) {
        groups.set(key, []);
      }
      groups.get(key).push(task);
    }
    return groups;
  }
  /**
   * Generate ghost occurrences for recurring tasks within a date range
   */
  static generateRecurringOccurrences(tasks, rangeStart, rangeEnd) {
    var _a;
    const ghosts = [];
    for (const task of tasks) {
      if (!task.repeat || task.repeatParentId || task.status >= 2 || !task.dueDate) {
        continue;
      }
      const occurrences = RRuleParser.generateOccurrences(
        {
          id: task.id,
          filePath: task.filePath,
          title: task.title,
          dueDate: task.dueDate,
          startDate: task.startDate,
          duration: task.duration,
          priority: task.priority,
          status: task.status,
          isAllDay: task.isAllDay,
          tags: task.tags,
          group: task.group,
          repeat: task.repeat,
          repeatParentId: task.repeatParentId
        },
        rangeStart,
        rangeEnd
      );
      for (const occ of occurrences) {
        ghosts.push({
          id: occ.id,
          filePath: occ.filePath,
          line: -1,
          title: occ.title,
          status: 0 /* Pending */,
          priority: occ.priority,
          tags: (_a = occ.tags) != null ? _a : [],
          dueDate: occ.dueDate,
          startDate: occ.startDate,
          duration: occ.duration,
          isAllDay: occ.isAllDay,
          repeat: task.repeat,
          repeatParentId: task.id,
          group: occ.group,
          isGhost: true
        });
      }
    }
    return ghosts;
  }
  /**
   * Parse date range string
   */
  static parseDateRange(rangeStr) {
    const today = /* @__PURE__ */ new Date();
    const todayStr = this.toDateString(today);
    switch (rangeStr.toLowerCase()) {
      case "today":
        return { start: todayStr, end: todayStr };
      case "tomorrow":
        const tomorrow = new Date(today);
        tomorrow.setDate(tomorrow.getDate() + 1);
        return { start: this.toDateString(tomorrow), end: this.toDateString(tomorrow) };
      case "week":
      case "thisweek":
        const startOfWeek = new Date(today);
        startOfWeek.setDate(today.getDate() - today.getDay());
        const endOfWeek = new Date(startOfWeek);
        endOfWeek.setDate(startOfWeek.getDate() + 6);
        return {
          start: this.toDateString(startOfWeek),
          end: this.toDateString(endOfWeek)
        };
      case "month":
      case "thismonth":
        return {
          start: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-01`,
          end: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(
            new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate()
          ).padStart(2, "0")}`
        };
      default:
        const parts = rangeStr.split(",");
        if (parts.length === 2) {
          return { start: parts[0].trim(), end: parts[1].trim() };
        }
        return { start: todayStr, end: todayStr };
    }
  }
  static getStatusLabel(status) {
    switch (status) {
      case 0 /* Pending */:
        return "Pending";
      case 1 /* InProgress */:
        return "In Progress";
      case 2 /* Completed */:
        return "Completed";
      case 3 /* Cancelled */:
        return "Cancelled";
      default:
        return "Unknown";
    }
  }
  static getPriorityLabel(priority) {
    switch (priority) {
      case 3 /* Urgent */:
        return "Urgent";
      case 2 /* High */:
        return "High";
      case 1 /* Medium */:
        return "Medium";
      case 0 /* None */:
        return "None";
      case -1 /* Low */:
        return "Low";
      default:
        return "Unknown";
    }
  }
  static compareDates(a, b) {
    if (!a && !b) return 0;
    if (!a) return 1;
    if (!b) return -1;
    return a.localeCompare(b);
  }
  static toDateString(date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}-${m}-${d}`;
  }
};

// src/vault/TaskFileManager.ts
var import_obsidian = require("obsidian");

// src/vault/FrontmatterParser.ts
var FrontmatterParser = class {
  /**
   * Parse frontmatter from markdown content
   * Returns { frontmatter, content } where content is the markdown without frontmatter
   */
  static parse(content) {
    const frontmatterRegex = /^---\n([\s\S]*?)\n---/;
    const match = content.match(frontmatterRegex);
    if (!match) {
      return { frontmatter: {}, content };
    }
    const frontmatterStr = match[1];
    const remainingContent = content.slice(match[0].length).trimStart();
    return {
      frontmatter: this.parseYaml(frontmatterStr),
      content: remainingContent
    };
  }
  /**
   * Simple YAML parser (handles basic key-value, arrays, and nested objects)
   */
  static parseYaml(yaml) {
    const result = {};
    const lines = yaml.split("\n");
    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      i++;
      if (!line.trim() || line.trim().startsWith("#")) continue;
      const colonIdx = line.indexOf(":");
      if (colonIdx <= 0) continue;
      const key = line.slice(0, colonIdx).trim();
      const value = line.slice(colonIdx + 1).trim();
      if (value !== "") {
        result[key] = this.parseYamlValue(value);
        continue;
      }
      const indentedLines = [];
      while (i < lines.length) {
        const nextLine = lines[i];
        if (nextLine.startsWith("  ") && nextLine.trim()) {
          indentedLines.push(nextLine);
          i++;
        } else {
          break;
        }
      }
      if (indentedLines.length === 0) {
        result[key] = "";
        continue;
      }
      if (indentedLines.every((l) => l.trimStart().startsWith("- "))) {
        result[key] = indentedLines.map((l) => this.parseYamlValue(l.trimStart().slice(2).trim()));
      } else {
        const obj = {};
        for (const indentedLine of indentedLines) {
          const innerColonIdx = indentedLine.indexOf(":");
          if (innerColonIdx > 0) {
            const innerKey = indentedLine.slice(2, innerColonIdx).trim();
            const innerValue = indentedLine.slice(innerColonIdx + 1).trim();
            obj[innerKey] = this.parseYamlValue(innerValue);
          }
        }
        result[key] = obj;
      }
    }
    return result;
  }
  /**
   * Parse a YAML value string into appropriate type
   */
  static parseYamlValue(value) {
    if (!value) return "";
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      return value.slice(1, -1);
    }
    if (value === "true") return true;
    if (value === "false") return false;
    if (value === "null" || value === "~") return null;
    const num = Number(value);
    if (!isNaN(num) && value !== "") return num;
    return value;
  }
  /**
   * Extract task-related frontmatter fields
   */
  static extractTaskFields(frontmatter) {
    const fields = {};
    if (typeof frontmatter.group === "string") {
      fields.group = frontmatter.group;
    }
    if (Array.isArray(frontmatter.tags)) {
      fields.tags = frontmatter.tags.map(String);
    } else if (typeof frontmatter.tags === "string") {
      fields.tags = frontmatter.tags.split(",").map((t) => t.trim());
    }
    if (typeof frontmatter.due === "string") {
      fields.dueDate = frontmatter.due;
    } else if (typeof frontmatter.dueDate === "string") {
      fields.dueDate = frontmatter.dueDate;
    }
    if (typeof frontmatter.start === "string") {
      fields.startDate = frontmatter.start;
    } else if (typeof frontmatter.startDate === "string") {
      fields.startDate = frontmatter.startDate;
    }
    if (typeof frontmatter.repeat === "string") {
      fields.repeat = RRuleParser.fromRRule(frontmatter.repeat);
    }
    if (typeof frontmatter.duration === "number") {
      fields.duration = frontmatter.duration;
    }
    if (typeof frontmatter.allDay === "boolean") {
      fields.isAllDay = frontmatter.allDay;
    }
    return fields;
  }
  /**
   * Serialize frontmatter back to YAML string
   */
  static stringify(frontmatter) {
    const lines = ["---"];
    for (const [key, value] of Object.entries(frontmatter)) {
      if (value === void 0 || value === null) continue;
      if (Array.isArray(value)) {
        lines.push(`${key}:`);
        for (const item of value) {
          lines.push(`  - ${this.stringifyYamlValue(item)}`);
        }
      } else {
        lines.push(`${key}: ${this.stringifyYamlValue(value)}`);
      }
    }
    lines.push("---");
    return lines.join("\n");
  }
  /**
   * Stringify a single YAML value
   */
  static stringifyYamlValue(value) {
    if (typeof value === "string") {
      if (value.includes(":") || value.includes("#") || value.includes(",") || value.includes("'") || value.includes('"')) {
        return `"${value.replace(/"/g, '\\"')}"`;
      }
      return value;
    }
    return String(value);
  }
};

// src/vault/TaskFileManager.ts
var TaskFileManager = class {
  constructor(app, taskFolderPath) {
    this.app = app;
    this.taskFolderPath = (0, import_obsidian.normalizePath)(taskFolderPath);
  }
  /**
   * Read all tasks from the task folder
   */
  async readAllTasks() {
    const tasks = [];
    const taskFolder = this.app.vault.getAbstractFileByPath(this.taskFolderPath);
    if (!taskFolder) {
      try {
        await this.app.vault.createFolder(this.taskFolderPath);
      } catch (e) {
        return tasks;
      }
    }
    const files = this.app.vault.getMarkdownFiles();
    const taskFiles = files.filter((f) => f.path.startsWith(this.taskFolderPath));
    for (const file of taskFiles) {
      const fileTasks = await this.readTasksFromFile(file);
      tasks.push(...fileTasks);
    }
    return tasks;
  }
  /**
   * Read tasks from a specific markdown file
   */
  async readTasksFromFile(file) {
    const content = await this.app.vault.read(file);
    const { content: bodyContent } = FrontmatterParser.parse(content);
    const lines = bodyContent.split("\n");
    const tasks = [];
    for (let i = 0; i < lines.length; i++) {
      const task = TaskManager.parseTaskLine(lines[i], file.path, i);
      if (task) {
        tasks.push(task);
      }
    }
    return tasks;
  }
  /**
   * Create a new task in a file
   */
  async createTask(task) {
    const targetFile = await this.getTargetFile(task.group);
    if (!targetFile) return null;
    const content = await this.app.vault.read(targetFile);
    const { frontmatter, content: bodyContent } = FrontmatterParser.parse(content);
    const lines = bodyContent.split("\n");
    const insertLine = lines.length > 0 && lines[lines.length - 1].trim() === "" ? lines.length - 1 : lines.length;
    const taskLine = TaskManager.serializeTask({
      ...task,
      id: "",
      filePath: targetFile.path,
      line: insertLine
    });
    lines.splice(insertLine, 0, taskLine);
    const newContent = Object.keys(frontmatter).length > 0 ? `${FrontmatterParser.stringify(frontmatter)}

${lines.join("\n")}` : lines.join("\n");
    await this.app.vault.modify(targetFile, newContent);
    return {
      ...task,
      id: `${targetFile.path}:${insertLine}`,
      filePath: targetFile.path,
      line: insertLine
    };
  }
  /**
   * Update an existing task
   */
  async updateTask(task) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!file) return false;
    const content = await this.app.vault.read(file);
    const { frontmatter, content: bodyContent } = FrontmatterParser.parse(content);
    const lines = bodyContent.split("\n");
    if (task.line < 0 || task.line >= lines.length) return false;
    lines[task.line] = TaskManager.serializeTask(task);
    const newContent = Object.keys(frontmatter).length > 0 ? `${FrontmatterParser.stringify(frontmatter)}

${lines.join("\n")}` : lines.join("\n");
    await this.app.vault.modify(file, newContent);
    return true;
  }
  /**
   * Delete a task
   */
  async deleteTask(task) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!file) return false;
    const content = await this.app.vault.read(file);
    const { frontmatter, content: bodyContent } = FrontmatterParser.parse(content);
    const lines = bodyContent.split("\n");
    if (task.line < 0 || task.line >= lines.length) return false;
    lines.splice(task.line, 1);
    const newContent = Object.keys(frontmatter).length > 0 ? `${FrontmatterParser.stringify(frontmatter)}

${lines.join("\n")}` : lines.join("\n");
    await this.app.vault.modify(file, newContent);
    return true;
  }
  /**
   * Toggle task status (pending -> in-progress -> completed)
   */
  async toggleTaskStatus(task) {
    let newStatus;
    switch (task.status) {
      case 0 /* Pending */:
        newStatus = 1 /* InProgress */;
        break;
      case 1 /* InProgress */:
        newStatus = 2 /* Completed */;
        break;
      case 2 /* Completed */:
        newStatus = 0 /* Pending */;
        break;
      default:
        newStatus = 0 /* Pending */;
    }
    const updatedTask = { ...task, status: newStatus };
    if (newStatus === 2 /* Completed */) {
      const today = /* @__PURE__ */ new Date();
      updatedTask.completedDate = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}`;
    } else {
      updatedTask.completedDate = void 0;
    }
    return this.updateTask(updatedTask);
  }
  /**
   * Get or create the target file for a task
   */
  async getTargetFile(group) {
    let targetPath;
    if (group) {
      targetPath = (0, import_obsidian.normalizePath)(`${this.taskFolderPath}/${group}.md`);
    } else {
      targetPath = (0, import_obsidian.normalizePath)(`${this.taskFolderPath}/tasks.md`);
    }
    let file = this.app.vault.getAbstractFileByPath(targetPath);
    if (!file) {
      try {
        const content = "";
        await this.app.vault.create(targetPath, content);
        file = this.app.vault.getAbstractFileByPath(targetPath);
      } catch (e) {
        return null;
      }
    }
    return file;
  }
  /**
   * Get all unique group names from tasks
   */
  async getGroupNames() {
    const tasks = await this.readAllTasks();
    const groups = /* @__PURE__ */ new Set();
    for (const task of tasks) {
      if (task.group) {
        groups.add(task.group);
      }
    }
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      if (file.path.startsWith(this.taskFolderPath) && file.path !== this.taskFolderPath) {
        const fileName = file.basename;
        if (fileName !== "tasks") {
          groups.add(fileName);
        }
      }
    }
    return Array.from(groups).sort();
  }
  /**
   * Get all unique tags from tasks
   */
  async getTagNames() {
    const tasks = await this.readAllTasks();
    const tags = /* @__PURE__ */ new Set();
    for (const task of tasks) {
      for (const tag of task.tags) {
        tags.add(tag);
      }
    }
    return Array.from(tags).sort();
  }
};

// src/views/ViewRenderer.ts
var import_obsidian2 = require("obsidian");

// src/views/TableView.ts
var TableView = class {
  static render(container, tasks, params, onTaskUpdate) {
    const table = container.createEl("table", { cls: "task-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    const columns = [
      { id: "checkbox", title: "", sortable: false },
      { id: "title", title: "Task", sortable: true },
      { id: "dueDate", title: "Due", sortable: true },
      { id: "priority", title: "Priority", sortable: true },
      { id: "tags", title: "Tags", sortable: false },
      { id: "group", title: "Group", sortable: true },
      { id: "actions", title: "", sortable: false }
    ];
    for (const col of columns) {
      const th = headerRow.createEl("th", { cls: `task-table-header task-table-header-${col.id}` });
      if (col.sortable) {
        th.style.cursor = "pointer";
        th.textContent = col.title;
        th.addEventListener("click", () => {
        });
      } else {
        th.textContent = col.title;
      }
    }
    const tbody = table.createEl("tbody");
    if (tasks.length === 0) {
      const emptyRow = tbody.createEl("tr");
      const emptyCell = emptyRow.createEl("td", {
        attr: { colspan: String(columns.length) },
        cls: "task-table-empty"
      });
      emptyCell.textContent = "No tasks found. Create one with the button above.";
      return;
    }
    for (const task of tasks) {
      const row = tbody.createEl("tr", {
        cls: `task-table-row task-table-row-${this.getStatusClass(task.status)}`
      });
      const checkboxCell = row.createEl("td", { cls: "task-table-cell task-table-cell-checkbox" });
      const checkbox = checkboxCell.createEl("input", {
        type: "checkbox",
        cls: "task-table-checkbox"
      });
      checkbox.checked = task.status === 2 /* Completed */;
      checkbox.addEventListener("change", async () => {
        await onTaskUpdate({
          ...task,
          status: checkbox.checked ? 2 /* Completed */ : 0 /* Pending */,
          completedDate: checkbox.checked ? (/* @__PURE__ */ new Date()).toISOString().split("T")[0] : void 0
        });
      });
      const titleCell = row.createEl("td", { cls: "task-table-cell task-table-cell-title" });
      titleCell.textContent = task.title;
      if (task.isGhost) {
        titleCell.addClass("task-table-ghost");
      }
      const dueDateCell = row.createEl("td", { cls: "task-table-cell task-table-cell-dueDate" });
      if (task.dueDate) {
        const dateStr = task.dueDate.split(" ")[0];
        dueDateCell.textContent = this.formatDate(dateStr);
        if (this.isOverdue(task)) {
          dueDateCell.addClass("task-table-overdue");
        }
      }
      const priorityCell = row.createEl("td", { cls: "task-table-cell task-table-cell-priority" });
      priorityCell.textContent = this.getPriorityIcon(task.priority);
      priorityCell.addClass(`task-table-priority-${this.getPriorityClass(task.priority)}`);
      const tagsCell = row.createEl("td", { cls: "task-table-cell task-table-cell-tags" });
      if (task.tags && task.tags.length > 0) {
        for (const tag of task.tags) {
          const tagEl = tagsCell.createEl("span", { cls: "task-table-tag" });
          tagEl.textContent = `#${tag}`;
        }
      }
      const groupCell = row.createEl("td", { cls: "task-table-cell task-table-cell-group" });
      if (task.group) {
        groupCell.textContent = task.group;
      }
      const actionsCell = row.createEl("td", { cls: "task-table-cell task-table-cell-actions" });
      const deleteBtn = actionsCell.createEl("button", {
        cls: "task-table-action-btn",
        text: "\xD7"
      });
      deleteBtn.title = "Delete task";
      deleteBtn.addEventListener("click", async () => {
        await onTaskUpdate({ ...task, status: 3 /* Cancelled */ });
      });
    }
  }
  static getStatusClass(status) {
    switch (status) {
      case 2 /* Completed */:
        return "completed";
      case 1 /* InProgress */:
        return "in-progress";
      case 3 /* Cancelled */:
        return "cancelled";
      default:
        return "pending";
    }
  }
  static getPriorityIcon(priority) {
    switch (priority) {
      case 3 /* Urgent */:
        return "\u23EB";
      case 2 /* High */:
        return "\u{1F53C}";
      case 1 /* Medium */:
        return "\u27A1\uFE0F";
      case -1 /* Low */:
        return "\u{1F53D}";
      default:
        return "\u2014";
    }
  }
  static getPriorityClass(priority) {
    switch (priority) {
      case 3 /* Urgent */:
        return "urgent";
      case 2 /* High */:
        return "high";
      case 1 /* Medium */:
        return "medium";
      case -1 /* Low */:
        return "low";
      default:
        return "none";
    }
  }
  static formatDate(dateStr) {
    const date = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
    const today = /* @__PURE__ */ new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);
    const taskDate = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
    taskDate.setHours(0, 0, 0, 0);
    if (taskDate.getTime() === today.getTime()) return "Today";
    if (taskDate.getTime() === tomorrow.getTime()) return "Tomorrow";
    if (taskDate.getTime() === yesterday.getTime()) return "Yesterday";
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  }
  static isOverdue(task) {
    if (!task.dueDate || task.status === 2 /* Completed */) return false;
    const dueDate = task.dueDate.split(" ")[0];
    const today = /* @__PURE__ */ new Date();
    today.setHours(0, 0, 0, 0);
    const due = /* @__PURE__ */ new Date(dueDate + "T00:00:00");
    due.setHours(0, 0, 0, 0);
    return due.getTime() < today.getTime();
  }
};

// src/views/KanbanView.ts
var KanbanView = class {
  static render(container, tasks, params, onTaskUpdate) {
    var _a;
    const board = container.createEl("div", { cls: "task-kanban-board" });
    const columns = [
      { id: "pending", title: "To Do", status: 0 /* Pending */, color: "#6c757d" },
      { id: "in-progress", title: "In Progress", status: 1 /* InProgress */, color: "#0d6efd" },
      { id: "completed", title: "Done", status: 2 /* Completed */, color: "#198754" }
    ];
    const showCompleted = (_a = params.showCompleted) != null ? _a : false;
    const visibleColumns = showCompleted ? columns : columns.filter((c) => c.status !== 2 /* Completed */);
    for (const col of visibleColumns) {
      const column = board.createEl("div", { cls: "task-kanban-column" });
      const columnHeader = column.createEl("div", { cls: "task-kanban-column-header" });
      const colorDot = columnHeader.createEl("span", {
        cls: "task-kanban-column-color"
      });
      colorDot.style.backgroundColor = col.color;
      columnHeader.createEl("span", {
        cls: "task-kanban-column-title",
        text: col.title
      });
      const columnTasks = tasks.filter((t) => t.status === col.status);
      const badge = columnHeader.createEl("span", {
        cls: "task-kanban-column-badge",
        text: String(columnTasks.length)
      });
      const columnBody = column.createEl("div", { cls: "task-kanban-column-body" });
      if (columnTasks.length === 0) {
        columnBody.createEl("div", {
          cls: "task-kanban-empty",
          text: "No tasks"
        });
      } else {
        for (const task of columnTasks) {
          const card = columnBody.createEl("div", {
            cls: `task-kanban-card task-kanban-card-${this.getPriorityClass(task.priority)}`
          });
          const cardTitle = card.createEl("div", {
            cls: "task-kanban-card-title",
            text: task.title
          });
          if (task.isGhost) {
            cardTitle.addClass("task-kanban-ghost");
          }
          const cardMeta = card.createEl("div", { cls: "task-kanban-card-meta" });
          if (task.dueDate) {
            const dueDateEl = cardMeta.createEl("span", {
              cls: "task-kanban-card-due"
            });
            const dateStr = task.dueDate.split(" ")[0];
            dueDateEl.textContent = this.formatDate(dateStr);
            if (this.isOverdue(task)) {
              dueDateEl.addClass("task-kanban-overdue");
            }
          }
          if (task.priority !== 0 /* None */) {
            cardMeta.createEl("span", {
              cls: "task-kanban-card-priority",
              text: this.getPriorityIcon(task.priority)
            });
          }
          if (task.tags && task.tags.length > 0) {
            const tagsEl = card.createEl("div", { cls: "task-kanban-card-tags" });
            for (const tag of task.tags.slice(0, 3)) {
              const tagEl = tagsEl.createEl("span", { cls: "task-kanban-tag" });
              tagEl.textContent = `#${tag}`;
            }
          }
          const cardActions = card.createEl("div", { cls: "task-kanban-card-actions" });
          if (col.status === 0 /* Pending */) {
            const startBtn = cardActions.createEl("button", {
              cls: "task-kanban-action-btn",
              text: "Start"
            });
            startBtn.addEventListener("click", async () => {
              await onTaskUpdate({ ...task, status: 1 /* InProgress */ });
            });
          } else if (col.status === 1 /* InProgress */) {
            const completeBtn = cardActions.createEl("button", {
              cls: "task-kanban-action-btn task-kanban-action-complete",
              text: "Complete"
            });
            completeBtn.addEventListener("click", async () => {
              await onTaskUpdate({
                ...task,
                status: 2 /* Completed */,
                completedDate: (/* @__PURE__ */ new Date()).toISOString().split("T")[0]
              });
            });
          } else if (col.status === 2 /* Completed */) {
            const reopenBtn = cardActions.createEl("button", {
              cls: "task-kanban-action-btn",
              text: "Reopen"
            });
            reopenBtn.addEventListener("click", async () => {
              await onTaskUpdate({ ...task, status: 0 /* Pending */, completedDate: void 0 });
            });
          }
        }
      }
    }
  }
  static getPriorityClass(priority) {
    switch (priority) {
      case 3 /* Urgent */:
        return "urgent";
      case 2 /* High */:
        return "high";
      case 1 /* Medium */:
        return "medium";
      case -1 /* Low */:
        return "low";
      default:
        return "none";
    }
  }
  static getPriorityIcon(priority) {
    switch (priority) {
      case 3 /* Urgent */:
        return "\u23EB";
      case 2 /* High */:
        return "\u{1F53C}";
      case 1 /* Medium */:
        return "\u27A1\uFE0F";
      case -1 /* Low */:
        return "\u{1F53D}";
      default:
        return "";
    }
  }
  static formatDate(dateStr) {
    const date = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
    const today = /* @__PURE__ */ new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);
    const taskDate = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
    taskDate.setHours(0, 0, 0, 0);
    if (taskDate.getTime() === today.getTime()) return "Today";
    if (taskDate.getTime() === tomorrow.getTime()) return "Tomorrow";
    if (taskDate.getTime() === yesterday.getTime()) return "Yesterday";
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  }
  static isOverdue(task) {
    if (!task.dueDate || task.status === 2 /* Completed */) return false;
    const dueDate = task.dueDate.split(" ")[0];
    const today = /* @__PURE__ */ new Date();
    today.setHours(0, 0, 0, 0);
    const due = /* @__PURE__ */ new Date(dueDate + "T00:00:00");
    due.setHours(0, 0, 0, 0);
    return due.getTime() < today.getTime();
  }
};

// src/views/CalendarView.ts
var CalendarView = class {
  static render(container, tasks, params, onTaskUpdate) {
    var _a;
    const calendar = container.createEl("div", { cls: "task-calendar" });
    const today = /* @__PURE__ */ new Date();
    const year = today.getFullYear();
    const month = today.getMonth();
    const header = calendar.createEl("div", { cls: "task-calendar-header" });
    const prevBtn = header.createEl("button", { cls: "task-calendar-nav-btn", text: "\u2190" });
    const titleEl = header.createEl("span", {
      cls: "task-calendar-title",
      text: today.toLocaleDateString("en-US", { month: "long", year: "numeric" })
    });
    const nextBtn = header.createEl("button", { cls: "task-calendar-nav-btn", text: "\u2192" });
    const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    const weekdayHeader = calendar.createEl("div", { cls: "task-calendar-weekdays" });
    for (const day of weekdays) {
      weekdayHeader.createEl("div", { cls: "task-calendar-weekday", text: day });
    }
    const grid = calendar.createEl("div", { cls: "task-calendar-grid" });
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startOffset = firstDay.getDay();
    const daysInMonth = lastDay.getDate();
    const prevMonthLastDay = new Date(year, month, 0).getDate();
    for (let i = startOffset - 1; i >= 0; i--) {
      const dayNum = prevMonthLastDay - i;
      const cell = grid.createEl("div", { cls: "task-calendar-cell task-calendar-cell-other-month" });
      cell.createEl("span", { cls: "task-calendar-cell-day", text: String(dayNum) });
    }
    const monthStart = `${year}-${String(month + 1).padStart(2, "0")}-01`;
    const monthEnd = `${year}-${String(month + 1).padStart(2, "0")}-${String(daysInMonth).padStart(2, "0")}`;
    const tasksByDate = /* @__PURE__ */ new Map();
    for (const task of tasks) {
      if (task.dueDate) {
        const dateStr = task.dueDate.split(" ")[0];
        if (dateStr >= monthStart && dateStr <= monthEnd) {
          if (!tasksByDate.has(dateStr)) {
            tasksByDate.set(dateStr, []);
          }
          tasksByDate.get(dateStr).push(task);
        }
      }
    }
    const todayStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}`;
    for (let day = 1; day <= daysInMonth; day++) {
      const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
      const cell = grid.createEl("div", {
        cls: `task-calendar-cell${dateStr === todayStr ? " task-calendar-cell-today" : ""}`
      });
      const dayNum = cell.createEl("span", { cls: "task-calendar-cell-day", text: String(day) });
      if (dateStr === todayStr) {
        dayNum.addClass("task-calendar-cell-day-today");
      }
      const dayTasks = (_a = tasksByDate.get(dateStr)) != null ? _a : [];
      for (const task of dayTasks) {
        const taskEl = cell.createEl("div", {
          cls: `task-calendar-task task-calendar-task-${this.getStatusClass(task.status)}`
        });
        taskEl.textContent = task.title;
        taskEl.title = task.title;
        taskEl.addEventListener("click", async () => {
          const newStatus = task.status === 0 /* Pending */ ? 1 /* InProgress */ : task.status === 1 /* InProgress */ ? 2 /* Completed */ : 0 /* Pending */;
          await onTaskUpdate({
            ...task,
            status: newStatus,
            completedDate: newStatus === 2 /* Completed */ ? (/* @__PURE__ */ new Date()).toISOString().split("T")[0] : void 0
          });
        });
      }
    }
    const totalCells = startOffset + daysInMonth;
    const remainingCells = 7 - totalCells % 7;
    if (remainingCells < 7) {
      for (let i = 1; i <= remainingCells; i++) {
        const cell = grid.createEl("div", { cls: "task-calendar-cell task-calendar-cell-other-month" });
        cell.createEl("span", { cls: "task-calendar-cell-day", text: String(i) });
      }
    }
  }
  static getStatusClass(status) {
    switch (status) {
      case 2 /* Completed */:
        return "completed";
      case 1 /* InProgress */:
        return "in-progress";
      case 3 /* Cancelled */:
        return "cancelled";
      default:
        return "pending";
    }
  }
};

// src/views/ViewRenderer.ts
var ViewRenderer = class {
  /**
   * Parse code block parameters
   */
  static parseParams(source) {
    const params = {};
    const lines = source.split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const [key, ...valueParts] = trimmed.split(":");
      const value = valueParts.join(":").trim();
      switch (key.toLowerCase()) {
        case "view":
          params.view = value;
          break;
        case "groupby":
          params.groupBy = value;
          break;
        case "sortby":
          params.sortBy = value;
          break;
        case "sortorder":
          params.sortOrder = value;
          break;
        case "filter":
          params.filter = value;
          break;
        case "showcompleted":
          params.showCompleted = value.toLowerCase() === "true";
          break;
        case "showcancelled":
          params.showCancelled = value.toLowerCase() === "true";
          break;
        case "daterange":
          params.dateRange = value;
          break;
        case "limit":
          params.limit = parseInt(value, 10);
          break;
        case "groups":
          params.groups = value.split(",").map((g) => g.trim());
          break;
        case "tags":
          params.tags = value.split(",").map((t) => t.trim());
          break;
      }
    }
    return params;
  }
  /**
   * Render a view based on parameters
   */
  static renderView(el, tasks, params, ctx, onTaskUpdate, onTaskCreate) {
    const child = new ViewRenderChild(el, tasks, params, ctx, onTaskUpdate, onTaskCreate);
    ctx.addChild(child);
    return child;
  }
};
var ViewRenderChild = class extends import_obsidian2.MarkdownRenderChild {
  constructor(container, tasks, params, ctx, onTaskUpdate, onTaskCreate) {
    super(container);
    this.tasks = tasks;
    this.params = params;
    this.ctx = ctx;
    this.onTaskUpdate = onTaskUpdate;
    this.onTaskCreate = onTaskCreate;
  }
  onload() {
    this.render();
  }
  render() {
    var _a;
    this.containerEl.empty();
    this.containerEl.addClass("task-manager-view");
    const header = this.containerEl.createDiv({ cls: "task-manager-header" });
    header.createSpan({
      cls: "task-manager-title",
      text: `Task Manager (${(_a = this.params.view) != null ? _a : "table"})`
    });
    const createBtn = header.createEl("button", {
      cls: "task-manager-create-btn",
      text: "+ New Task"
    });
    createBtn.addEventListener("click", () => this.onTaskCreate());
    let filteredTasks = TaskManager.filterTasks(this.tasks, this.params);
    filteredTasks = TaskManager.sortTasks(
      filteredTasks,
      this.params.sortBy,
      this.params.sortOrder
    );
    if (this.params.dateRange) {
      const { start, end } = this.parseDateRange(this.params.dateRange);
      if (start && end) {
        const ghosts = TaskManager.generateRecurringOccurrences(
          this.tasks,
          start,
          end
        );
        filteredTasks = [...filteredTasks, ...ghosts];
      }
    }
    const viewContent = this.containerEl.createDiv({ cls: "task-manager-content" });
    switch (this.params.view) {
      case "kanban":
        KanbanView.render(viewContent, filteredTasks, this.params, this.onTaskUpdate);
        break;
      case "calendar":
        CalendarView.render(viewContent, filteredTasks, this.params, this.onTaskUpdate);
        break;
      case "table":
      default:
        TableView.render(viewContent, filteredTasks, this.params, this.onTaskUpdate);
        break;
    }
  }
  parseDateRange(rangeStr) {
    const today = /* @__PURE__ */ new Date();
    const todayStr = this.toDateString(today);
    switch (rangeStr.toLowerCase()) {
      case "today":
        return { start: todayStr, end: todayStr };
      case "tomorrow":
        const tomorrow = new Date(today);
        tomorrow.setDate(tomorrow.getDate() + 1);
        return { start: this.toDateString(tomorrow), end: this.toDateString(tomorrow) };
      case "week":
      case "thisweek":
        const startOfWeek = new Date(today);
        startOfWeek.setDate(today.getDate() - today.getDay());
        const endOfWeek = new Date(startOfWeek);
        endOfWeek.setDate(startOfWeek.getDate() + 6);
        return {
          start: this.toDateString(startOfWeek),
          end: this.toDateString(endOfWeek)
        };
      case "month":
      case "thismonth":
        return {
          start: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-01`,
          end: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(
            new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate()
          ).padStart(2, "0")}`
        };
      default:
        const parts = rangeStr.split(",");
        if (parts.length === 2) {
          return { start: parts[0].trim(), end: parts[1].trim() };
        }
        return { start: todayStr, end: todayStr };
    }
  }
  toDateString(date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}-${m}-${d}`;
  }
};

// src/ui/CreateTaskModal.ts
var import_obsidian3 = require("obsidian");
var RFC_DAYS = ["SU", "MO", "TU", "WE", "TH", "FR", "SA"];
var DAY_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
var CreateTaskModal = class extends import_obsidian3.Modal {
  constructor(app, initialData, onSubmit, options = {}) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o;
    super(app);
    this.startDateInputEl = null;
    this.dueDateInputEl = null;
    this.enableDateRange = false;
    this.onSubmit = onSubmit;
    this.groupNames = (_a = options.groupNames) != null ? _a : [];
    this.data = {
      title: (_b = initialData.title) != null ? _b : "",
      description: (_c = initialData.description) != null ? _c : "",
      status: (_d = initialData.status) != null ? _d : 0 /* Pending */,
      priority: (_e = initialData.priority) != null ? _e : 0 /* None */,
      tags: initialData.tags ? [...initialData.tags] : [],
      dueDate: (_f = initialData.dueDate) != null ? _f : "",
      dueTime: (_g = initialData.dueTime) != null ? _g : "",
      startDate: (_h = initialData.startDate) != null ? _h : "",
      startTime: (_i = initialData.startTime) != null ? _i : "",
      duration: (_j = initialData.duration) != null ? _j : 30,
      isAllDay: initialData.isAllDay !== void 0 ? initialData.isAllDay : true,
      repeat: initialData.repeat,
      group: (_k = initialData.group) != null ? _k : "",
      type: (_l = initialData.type) != null ? _l : "task",
      content: (_m = initialData.content) != null ? _m : "",
      enableDateRange: (_n = initialData.enableDateRange) != null ? _n : false
    };
    this.enableDateRange = (_o = initialData.enableDateRange) != null ? _o : false;
  }
  async onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.empty();
    modalEl.addClass("kanban-board-modal-host");
    contentEl.addClass("task-edit-modal");
    const header = modalEl.createDiv({ cls: "kanban-modal-header" });
    modalEl.insertBefore(header, contentEl);
    header.createEl("h2", { cls: "kanban-modal-title", text: "New Task" });
    const form = contentEl.createDiv({ cls: "tm-form" });
    this.buildForm(form);
    const footer = modalEl.createDiv({ cls: "kanban-modal-footer" });
    footer.createEl("button", { cls: "km-btn", text: "Cancel" }).onclick = () => this.close();
    const submitBtn = footer.createEl("button", { cls: "km-btn km-btn-cta", text: "Create Task" });
    submitBtn.onclick = async () => {
      if (!this.data.title.trim()) {
        new import_obsidian3.Notice("Task title cannot be empty");
        return;
      }
      submitBtn.textContent = "Creating\u2026";
      submitBtn.setAttribute("disabled", "true");
      try {
        await this.onSubmit(this.data);
        this.close();
      } catch (e) {
        new import_obsidian3.Notice("Failed to create task");
        submitBtn.textContent = "Create Task";
        submitBtn.removeAttribute("disabled");
      }
    };
    this.modalEl.addEventListener("keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
        e.preventDefault();
        submitBtn.click();
      }
    });
  }
  onClose() {
    this.contentEl.empty();
    this.modalEl.removeClass("kanban-board-modal-host");
  }
  buildForm(form) {
    const titleWrap = form.createDiv({ cls: "tm-hero-title-wrap" });
    const titleInput = titleWrap.createEl("input", { cls: "tm-hero-title", type: "text" });
    titleInput.placeholder = "What needs to be done?";
    titleInput.value = this.data.title;
    titleInput.addEventListener("input", () => {
      this.data.title = titleInput.value;
    });
    this.section(form, "Dates", (s) => {
      var _a;
      const grid = s.createDiv({ cls: "tm-dates-grid" });
      this.dateField(
        grid,
        "Start",
        this.data.startDate,
        this.data.startTime,
        (d) => {
          this.data.startDate = d;
        },
        (t) => {
          this.data.startTime = t;
        }
      );
      this.dateField(
        grid,
        "Due",
        this.data.dueDate,
        this.data.dueTime,
        (d) => {
          this.data.dueDate = d;
        },
        (t) => {
          this.data.dueTime = t;
        }
      );
      const allDayWrap = s.createDiv({ cls: "tm-allday-wrap" });
      const label = allDayWrap.createEl("label", { cls: "tm-allday-label" });
      const cb = label.createEl("input", { type: "checkbox", cls: "tm-allday-checkbox" });
      cb.checked = (_a = this.data.isAllDay) != null ? _a : true;
      label.createSpan({ text: "All Day" });
      cb.addEventListener("change", () => {
        this.data.isAllDay = cb.checked;
      });
    });
    this.section(form, "Priority", (s) => {
      this.priorityPills(s, this.data.priority, (v) => {
        this.data.priority = v;
      });
    });
    this.section(form, "Tags", (s) => {
      const input = s.createEl("input", { cls: "km-input", type: "text" });
      input.placeholder = "work, urgent, review\u2026";
      input.value = this.data.tags.join(", ");
      input.addEventListener("input", () => {
        this.data.tags = input.value.split(",").map((t) => t.trim()).filter(Boolean);
      });
    });
    this.section(form, "Group", (s) => {
      var _a;
      const wrap = s.createDiv({ cls: "tm-autocomplete-wrap" });
      wrap.style.position = "relative";
      const input = wrap.createEl("input", { cls: "km-input", type: "text" });
      input.placeholder = "Inbox";
      input.value = (_a = this.data.group) != null ? _a : "";
      input.addEventListener("input", () => {
        this.data.group = input.value.trim();
      });
      const dropdown = wrap.createDiv({ cls: "tm-autocomplete-dropdown" });
      dropdown.style.display = "none";
      input.addEventListener("focus", () => {
        dropdown.empty();
        const filtered = this.groupNames.filter(
          (g) => g.toLowerCase().includes(input.value.toLowerCase())
        );
        if (filtered.length === 0) {
          dropdown.style.display = "none";
          return;
        }
        for (const item of filtered) {
          const option = dropdown.createDiv({ cls: "tm-autocomplete-item" });
          option.textContent = item;
          option.addEventListener("mousedown", () => {
            input.value = item;
            this.data.group = item;
            dropdown.style.display = "none";
          });
        }
        dropdown.style.display = "flex";
      });
      input.addEventListener("blur", () => {
        setTimeout(() => {
          dropdown.style.display = "none";
        }, 200);
      });
    });
    this.section(form, "Duration (minutes)", (s) => {
      var _a;
      const input = s.createEl("input", { cls: "km-input", type: "number" });
      input.min = "1";
      input.placeholder = "30";
      input.value = String((_a = this.data.duration) != null ? _a : 30);
      input.oninput = () => {
        const val = parseInt(input.value);
        if (!isNaN(val) && val > 0) {
          this.data.duration = val;
        }
      };
    });
    const repeatWrap = form.createDiv({ cls: "tm-repeat-wrap" });
    this.renderRepeatPanel(repeatWrap);
    this.section(form, "Description", (s) => {
      var _a;
      const ta = s.createEl("textarea", { cls: "tm-textarea" });
      ta.placeholder = "Add details, notes, or context\u2026";
      ta.value = (_a = this.data.content) != null ? _a : "";
      ta.rows = 3;
      ta.oninput = () => {
        this.data.content = ta.value;
      };
    });
  }
  section(parent, title, builder) {
    const section = parent.createDiv({ cls: "tm-form-section" });
    section.createEl("h3", { cls: "tm-form-section-title", text: title });
    builder(section);
  }
  dateField(container, label, dateValue, timeValue, onDateChange, onTimeChange) {
    const field = container.createDiv({ cls: "tm-date-field" });
    field.createEl("label", { cls: "tm-date-field-label", text: label });
    const dateInput = field.createEl("input", {
      cls: "tm-date-input",
      type: "date"
    });
    dateInput.value = dateValue != null ? dateValue : "";
    dateInput.addEventListener("change", () => {
      onDateChange(dateInput.value);
    });
    if (label === "Start") {
      this.startDateInputEl = dateInput;
    } else {
      this.dueDateInputEl = dateInput;
    }
    const timeInput = field.createEl("input", {
      cls: "tm-time-input",
      type: "time"
    });
    timeInput.value = timeValue != null ? timeValue : "";
    timeInput.style.display = this.data.isAllDay ? "none" : "";
    timeInput.addEventListener("change", () => {
      onTimeChange(timeInput.value);
    });
  }
  priorityPills(container, current, onChange) {
    const wrap = container.createDiv({ cls: "tm-priority-pills" });
    const priorities = [
      { value: -1 /* Low */, label: "Low", icon: "\u{1F53D}" },
      { value: 0 /* None */, label: "None", icon: "\u2014" },
      { value: 1 /* Medium */, label: "Medium", icon: "\u27A1\uFE0F" },
      { value: 2 /* High */, label: "High", icon: "\u{1F53C}" },
      { value: 3 /* Urgent */, label: "Urgent", icon: "\u23EB" }
    ];
    for (const p of priorities) {
      const pill = wrap.createEl("button", {
        cls: `tm-priority-pill${current === p.value ? " is-active" : ""}`,
        text: `${p.icon} ${p.label}`
      });
      pill.addEventListener("click", () => {
        wrap.querySelectorAll(".tm-priority-pill").forEach((el) => el.removeClass("is-active"));
        pill.addClass("is-active");
        onChange(p.value);
      });
    }
  }
  renderRepeatPanel(container) {
    var _a, _b, _c, _d;
    container.empty();
    if (!this.data.repeat) {
      const addBtn = container.createEl("button", { cls: "tm-add-btn" });
      (0, import_obsidian3.setIcon)(addBtn.createSpan({ cls: "tm-add-btn-icon" }), "repeat");
      addBtn.createSpan({ text: "Add recurrence" });
      addBtn.onclick = () => {
        this.data.repeat = { freq: "WEEKLY", interval: 1 };
        this.renderRepeatPanel(container);
      };
      return;
    }
    const panel = container.createDiv({ cls: "tm-repeat-panel" });
    const row1 = panel.createDiv({ cls: "tm-repeat-row" });
    row1.createEl("span", { cls: "tm-repeat-row-label", text: "Repeat" });
    const freqSel = row1.createEl("select", { cls: "km-select" });
    const freqs = [
      ["DAILY", "Daily"],
      ["WEEKLY", "Weekly"],
      ["MONTHLY", "Monthly"],
      ["YEARLY", "Yearly"]
    ];
    for (const [v, l] of freqs) {
      const o = freqSel.createEl("option", { value: v, text: l });
      if (v === ((_a = this.data.repeat) == null ? void 0 : _a.freq)) o.selected = true;
    }
    freqSel.onchange = () => {
      if (this.data.repeat) {
        this.data.repeat = { freq: freqSel.value, interval: this.data.repeat.interval };
      }
      this.renderRepeatPanel(container);
    };
    row1.createEl("span", { text: "every", cls: "tm-repeat-row-label" });
    const intervalInput = row1.createEl("input", {
      cls: "km-input tm-interval-input",
      type: "number"
    });
    intervalInput.min = "1";
    intervalInput.value = String((_c = (_b = this.data.repeat) == null ? void 0 : _b.interval) != null ? _c : 1);
    intervalInput.oninput = () => {
      const n = parseInt(intervalInput.value);
      if (this.data.repeat && n > 0) this.data.repeat.interval = n;
    };
    const unitLabels = {
      DAILY: "day(s)",
      WEEKLY: "week(s)",
      MONTHLY: "month(s)",
      YEARLY: "year(s)"
    };
    row1.createEl("span", {
      text: unitLabels[this.data.repeat.freq],
      cls: "tm-repeat-row-label"
    });
    if (this.data.repeat.freq === "WEEKLY") {
      const dayRow = panel.createDiv({ cls: "tm-day-row" });
      const currentDays = new Set((_d = this.data.repeat.byday) != null ? _d : []);
      for (let i = 0; i < RFC_DAYS.length; i++) {
        const code = RFC_DAYS[i];
        const lbl = dayRow.createEl("label", {
          cls: "tm-day-pill" + (currentDays.has(code) ? " is-on" : "")
        });
        const chk = lbl.createEl("input", { type: "checkbox" });
        chk.checked = currentDays.has(code);
        lbl.createSpan({ text: DAY_LABELS[i].slice(0, 2) });
        chk.onchange = () => {
          if (!this.data.repeat) return;
          if (chk.checked) {
            currentDays.add(code);
            lbl.addClass("is-on");
          } else {
            currentDays.delete(code);
            lbl.removeClass("is-on");
          }
          this.data.repeat.byday = RFC_DAYS.filter((d) => currentDays.has(d));
        };
      }
    }
    if (this.data.repeat.freq === "MONTHLY") {
      const mRow = panel.createDiv({ cls: "tm-repeat-row" });
      mRow.createEl("span", { text: "On", cls: "tm-repeat-row-label" });
      const modeSel = mRow.createEl("select", { cls: "km-select" });
      const modes = [
        ["default", "Same day"],
        ["bymonthday", "Day number"],
        ["bynthweekday", "Nth weekday"]
      ];
      for (const [v, l] of modes) {
        const o = modeSel.createEl("option", { value: v, text: l });
        if (v === this.detectMonthlyMode(this.data.repeat)) o.selected = true;
      }
      modeSel.onchange = () => {
        if (!this.data.repeat) return;
        delete this.data.repeat.bymonthday;
        delete this.data.repeat.bysetpos;
        delete this.data.repeat.byday;
        if (modeSel.value === "bymonthday") this.data.repeat.bymonthday = [1];
        if (modeSel.value === "bynthweekday") {
          this.data.repeat.bysetpos = [1];
          this.data.repeat.byday = ["MO"];
        }
        this.renderRepeatPanel(container);
      };
    }
    const endCond = this.detectEndCondition(this.data.repeat);
    const endRow = panel.createDiv({ cls: "tm-repeat-row" });
    endRow.createEl("span", { text: "Ends", cls: "tm-repeat-row-label" });
    const endSel = endRow.createEl("select", { cls: "km-select" });
    const endOptions = [
      ["never", "Never"],
      ["until", "On date"],
      ["count", "After N times"]
    ];
    for (const [v, l] of endOptions) {
      const o = endSel.createEl("option", { value: v, text: l });
      if (v === endCond) o.selected = true;
    }
    endSel.onchange = () => {
      if (!this.data.repeat) return;
      delete this.data.repeat.until;
      delete this.data.repeat.count;
      if (endSel.value === "count") this.data.repeat.count = 10;
      this.renderRepeatPanel(container);
    };
    const removeRow = panel.createDiv({ cls: "tm-repeat-row" });
    const removeBtn = removeRow.createEl("button", {
      cls: "tm-remove-btn",
      text: "Remove recurrence"
    });
    removeBtn.onclick = () => {
      this.data.repeat = void 0;
      this.renderRepeatPanel(container);
    };
  }
  detectMonthlyMode(r) {
    var _a, _b, _c;
    if (!r) return "default";
    if (((_a = r.bysetpos) == null ? void 0 : _a.length) && ((_b = r.byday) == null ? void 0 : _b.length)) return "bynthweekday";
    if ((_c = r.bymonthday) == null ? void 0 : _c.length) return "bymonthday";
    return "default";
  }
  detectEndCondition(r) {
    if (!r) return "never";
    if (r.until) return "until";
    if (r.count != null) return "count";
    return "never";
  }
};

// src/settings/TaskManagerSettingsTab.ts
var import_obsidian4 = require("obsidian");
var TaskManagerSettingsTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Task folder").setDesc("Folder where task files are stored").addText(
      (text) => text.setPlaceholder("tasks").setValue(this.plugin.settings.taskFolderPath).onChange(async (value) => {
        this.plugin.settings.taskFolderPath = value || "tasks";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Default view").setDesc("Default view type for task blocks").addDropdown(
      (dropdown) => dropdown.addOption("table", "Table").addOption("kanban", "Kanban").addOption("calendar", "Calendar").setValue(this.plugin.settings.defaultView).onChange(async (value) => {
        this.plugin.settings.defaultView = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show completed tasks").setDesc("Include completed tasks in views by default").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCompletedByDefault).onChange(async (value) => {
        this.plugin.settings.showCompletedByDefault = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show cancelled tasks").setDesc("Include cancelled tasks in views by default").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCancelledByDefault).onChange(async (value) => {
        this.plugin.settings.showCancelledByDefault = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Date format").setDesc("Format for displaying dates").addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dateFormat).onChange(async (value) => {
        this.plugin.settings.dateFormat = value || "YYYY-MM-DD";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Start of week").setDesc("First day of the week (0 = Sunday, 1 = Monday)").addDropdown(
      (dropdown) => dropdown.addOption("0", "Sunday").addOption("1", "Monday").setValue(String(this.plugin.settings.startOfWeek)).onChange(async (value) => {
        this.plugin.settings.startOfWeek = parseInt(value, 10);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Default repeat frequency").setDesc("Default frequency for recurring tasks").addDropdown(
      (dropdown) => dropdown.addOption("DAILY", "Daily").addOption("WEEKLY", "Weekly").addOption("MONTHLY", "Monthly").addOption("YEARLY", "Yearly").setValue(this.plugin.settings.defaultRepeatFreq).onChange(async (value) => {
        this.plugin.settings.defaultRepeatFreq = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Enable Google Calendar").setDesc("Sync tasks with Google Calendar (requires API setup)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableGoogleCalendar).onChange(async (value) => {
        this.plugin.settings.enableGoogleCalendar = value;
        await this.plugin.saveSettings();
      })
    );
    if (this.plugin.settings.enableGoogleCalendar) {
      new import_obsidian4.Setting(containerEl).setName("Google Calendar ID").setDesc("Calendar ID for syncing (e.g., primary or your calendar email)").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("primary").setValue((_a = this.plugin.settings.googleCalendarId) != null ? _a : "").onChange(async (value) => {
            this.plugin.settings.googleCalendarId = value;
            await this.plugin.saveSettings();
          });
        }
      );
    }
    new import_obsidian4.Setting(containerEl).setName("Reset settings").setDesc("Reset all settings to defaults").addButton(
      (button) => button.setButtonText("Reset").setWarning().onClick(async () => {
        this.plugin.settings = this.plugin.getDefaultSettings();
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/main.ts
var TaskManagerPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.fileManager = null;
    this.tasks = [];
  }
  async onload() {
    await this.loadSettings();
    this.fileManager = new TaskFileManager(this.app, this.settings.taskFolderPath);
    this.registerMarkdownCodeBlockProcessor("task-manager", (source, el, ctx) => {
      this.renderCodeBlock(source, el, ctx);
    });
    this.registerMarkdownCodeBlockProcessor("tasks", (source, el, ctx) => {
      this.renderCodeBlock(source, el, ctx);
    });
    this.addRibbonIcon("check-square", "Create Task", () => {
      this.openCreateTaskModal();
    });
    this.addCommand({
      id: "create-task",
      name: "Create new task",
      callback: () => {
        this.openCreateTaskModal();
      }
    });
    this.addCommand({
      id: "toggle-task",
      name: "Toggle task status on current line",
      editorCallback: (editor, view) => {
        this.toggleTaskOnLine(editor, view);
      }
    });
    this.addSettingTab(new TaskManagerSettingsTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian5.TFile && file.path.startsWith(this.settings.taskFolderPath)) {
          this.refreshTasks();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian5.TFile && file.path.startsWith(this.settings.taskFolderPath)) {
          this.refreshTasks();
        }
      })
    );
    await this.refreshTasks();
  }
  onunload() {
  }
  /**
   * Load settings from disk
   */
  async loadSettings() {
    const data = await this.loadData();
    this.settings = {
      ...this.getDefaultSettings(),
      ...data
    };
  }
  /**
   * Save settings to disk
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Get default settings
   */
  getDefaultSettings() {
    return {
      taskFolderPath: "tasks",
      defaultTaskFile: "tasks.md",
      defaultView: "table",
      showCompletedByDefault: false,
      showCancelledByDefault: false,
      dateFormat: "YYYY-MM-DD",
      timeFormat: "HH:mm",
      use24HourTime: true,
      startOfWeek: 0,
      defaultRepeatFreq: "WEEKLY",
      defaultRepeatInterval: 1,
      enableGoogleCalendar: false,
      taskTypes: [
        { name: "task", icon: "check-square" },
        { name: "event", icon: "calendar" },
        { name: "note", icon: "file-text" }
      ]
    };
  }
  /**
   * Refresh tasks from vault
   */
  async refreshTasks() {
    if (!this.fileManager) return;
    this.tasks = await this.fileManager.readAllTasks();
  }
  /**
   * Render a code block view
   */
  renderCodeBlock(source, el, ctx) {
    const params = ViewRenderer.parseParams(source);
    if (!params.view) {
      params.view = this.settings.defaultView;
    }
    if (params.showCompleted === void 0) {
      params.showCompleted = this.settings.showCompletedByDefault;
    }
    if (params.showCancelled === void 0) {
      params.showCancelled = this.settings.showCancelledByDefault;
    }
    ViewRenderer.renderView(
      el,
      this.tasks,
      params,
      ctx,
      async (task) => {
        if (!this.fileManager) return;
        await this.fileManager.updateTask(task);
        await this.refreshTasks();
      },
      () => {
        this.openCreateTaskModal();
      }
    );
  }
  /**
   * Open the create task modal
   */
  openCreateTaskModal() {
    if (!this.fileManager) return;
    const modal = new CreateTaskModal(
      this.app,
      {
        status: 0 /* Pending */,
        priority: 0 /* None */,
        isAllDay: true,
        duration: 30
      },
      async (data) => {
        if (!this.fileManager) return;
        const task = {
          title: data.title,
          description: data.description,
          status: data.status,
          priority: data.priority,
          tags: data.tags,
          dueDate: this.combineDateAndTime(data.dueDate, data.dueTime),
          startDate: this.combineDateAndTime(data.startDate, data.startTime),
          duration: data.duration,
          isAllDay: data.isAllDay,
          repeat: data.repeat,
          group: data.group
        };
        await this.fileManager.createTask(task);
        await this.refreshTasks();
        new import_obsidian5.Notice("Task created");
      },
      {
        groupNames: []
        // Will be populated if needed
      }
    );
    modal.open();
  }
  /**
   * Toggle task status on the current editor line
   */
  toggleTaskOnLine(editor, view) {
    var _a, _b;
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const task = TaskManager.parseTaskLine(line, (_b = (_a = view.file) == null ? void 0 : _a.path) != null ? _b : "", cursor.line);
    if (!task) {
      new import_obsidian5.Notice("No task found on this line");
      return;
    }
    const newStatus = task.status === 0 /* Pending */ ? 1 /* InProgress */ : task.status === 1 /* InProgress */ ? 2 /* Completed */ : 0 /* Pending */;
    const updatedTask = {
      ...task,
      status: newStatus,
      completedDate: newStatus === 2 /* Completed */ ? (/* @__PURE__ */ new Date()).toISOString().split("T")[0] : void 0
    };
    const newLine = TaskManager.serializeTask(updatedTask);
    editor.setLine(cursor.line, newLine);
  }
  /**
   * Combine date and time strings
   */
  combineDateAndTime(date, time) {
    if (!date) return void 0;
    if (!time) return date;
    return `${date} ${time}`;
  }
};
